[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['denite.nvim']

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_ft = ['qf']

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'yarn install'
hook_add = '''
nmap <Leader>py <Plug>(PrettierAsync)
let g:prettier#autoformat = 1
let g:prettier#quickfix_enabled = 1
let g:prettier#exec_cmd_async = 1
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue PrettierAsync
'''
on_ft = ['typescript', 'javascript', 'css', 'json']
on_i = 1

[[plugins]]
repo = 'leafgarland/typescript-vim'
hook_add = '''
let g:typescript_indent_disable = 1
let g:typescript_compiler_binary = 'tsc'
let g:typescript_compiler_options = ''
autocmd FileType typescript :set makeprg=tsc
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow
'''
on_ft = ['typescript']

[[plugins]]
repo = 'jason0x43/vim-js-indent'
hook_add = '''
let g:js_indent_typescript = 1
'''
on_ft = ['javascript', 'typescript', 'html']

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
let g:go_version_warning = 0
let g:go_list_type = "quickfix"
'''
on_ft = ['go']
